#==========================================================
#= WebApp - Versione Base
#==========================================================
server:
  port: 8080
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  error:
    path: /error
    whitelabel:
      enabled: false    
      

      
#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always 
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5433/webapp
    username: postgres
    password: 123_Stella

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    
  # Abilita il logging di debug per Hibernate
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE